[workspace]
members = ["lintian-brush", "multiarch-hints", "lintian-brush-py"]

[workspace.package]
version = "0.150.0"

[workspace.dependencies]
breezyshim = "0.1.23"
pyo3 = "0.19"
debversion = ">=0.1.8"
serde_yaml = ">=0.8"
reqwest = "0.11"
log = "0.4"
lazy_static = "1.4"
serde = "1"
chrono = "0.4"
lazy-regex = "2"
env_logger = "0.10"
pyo3-file = ">=0.5"
clap = "<=4.2"
serde_json = "1"
tempfile = "3"
