[package]
name = "lintian-brush"
version = "0.149.0"
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "Automatic lintian issue fixer"
repository = "https://salsa.debian.org/jelmer/lintian-brush.git"
homepage = "https://salsa.debian.org/jelmer/lintian-brush"

[dependencies]
pyo3 = { version = "0.19", features = ["auto-initialize"], optional = true }
serde_json = { version = "1"}
serde_yaml = { version = ">=0.8" }
serde = { version = "1", features = ["derive"] }
distro-info = { version = ">=0.4.0" }
chrono = { version = "0.4" }
log = "0.4.19"
configparser = "3.0.2"
clap = { version = "4", features = ["derive", "env", "suggestions"], optional = true }
env_logger = { version = "0.10.0", optional = true }
lazy-regex = "3.0.0"
debversion = { version = "0.1.8" }

[features]
default = ["svp", "python", "cli"]
svp = []
python = ["dep:pyo3"]
cli = ["dep:clap", "dep:env_logger"]

[workspace]
members = ["multiarch-hints", "lintian-brush-py"]

[[bin]]
name = "lintian-brush"
required-features = ["cli"]
