[workspace]
# With resolve set to "2", dependent projects can't find debian-analyzer anymore.
resolver = "1"
members = ["lintian-brush", "multiarch-hints", "lintian-brush-py", "debianize", "analyzer", "scrub-obsolete", "transition-apply", "import-uncommitted"]

[workspace.package]
version = "0.158.0"

[workspace.dependencies]
breezyshim = { version = ">=0.1.205", features = ["dirty-tracker"] }
#breezyshim = { path = "../breezyshim/trunk", features = ["dirty-tracker"] }
pyo3 = ">=0.22"
debversion = ">=0.3.0"
serde_yaml = ">=0.8"
reqwest = ">=0.11"
log = "0.4"
lazy_static = "1"
serde = "1"
chrono = ">=0.4"
lazy-regex = ">=2"
env_logger = ">=0.10"
clap = "4,<5"
serde_json = "1"
tempfile = "3"
configparser = "3"
url = "2"
debian-copyright = ">=0.1.26"
debian-changelog = "0.2"
debian-control = ">=0.1.37"
deb822-lossless = "0.2"
pyo3-log = ">=0.11"
maplit = "1"
buildlog-consultant = ">=0.0.43"
upstream-ontologist = ">=0.1.43"
#upstream-ontologist = { git = "https://github.com/jelmer/upstream-ontologist" }
sqlx = ">=0.8"
semver = "1"
toml_edit = ">=0.22"
tokio = ">=1.39"
debian-analyzer = { path = "analyzer" }

#debian-control = { path = "../deb822-lossless/debian-control" }
#deb822-lossless = { path = "../deb822-lossless" }
