[package]
name = "lintian-brush"
version = "0.150.0"
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "Automatic lintian issue fixer"
repository = "https://salsa.debian.org/jelmer/lintian-brush.git"
homepage = "https://salsa.debian.org/jelmer/lintian-brush"

[dependencies]
pyo3 = { workspace = true, features = ["auto-initialize", "serde", "chrono"], optional = true }
serde_json = { version = "1"}
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
distro-info = { version = ">=0.4.0" }
chrono = { workspace = true }
log = { workspace = true }
configparser = "3.0.2"
clap = { version = "<=4.2", features = ["derive", "env", "suggestions", "cargo", "string"], optional = true }
env_logger = { workspace = true, optional = true }
lazy-regex = { workspace = true }
debversion = { workspace = true, features = ["python-debian"] }
pyo3-file = { workspace = true }
breezyshim = { workspace = true }
indicatif = "0.17"
tempfile = "3"
url = { version = "2", features = ["serde"] }
lazy_static = { workspace = true }

[features]
default = ["svp", "python", "cli"]
svp = []
python = ["dep:pyo3"]
cli = ["dep:clap", "dep:env_logger"]

[workspace]
members = ["multiarch-hints", "lintian-brush-py"]

[workspace.dependencies]
breezyshim = "0.1.22"
pyo3 = "0.19"
debversion = ">=0.1.8"
serde_yaml = ">=0.8"
reqwest = "0.11"
log = "0.4"
lazy_static = "1.4"
serde = "1"
chrono = "0.4"
lazy-regex = "2"
env_logger = "0.10"
pyo3-file = ">=0.5"

[[bin]]
name = "lintian-brush"
required-features = ["cli"]

[[bin]]
name = "detect-gbp-dch"
path = "src/bin/detect-gbp-dch.rs"
required-features = ["cli"]
