[workspace]
resolver = "2"
members = ["lintian-brush", "multiarch-hints", "lintian-brush-py", "debianize", "debianize-py", "analyzer"]

[workspace.package]
version = "0.157.2"

[workspace.dependencies]
breezyshim = ">=0.1.58"
pyo3 = ">=0.20"
debversion = ">=0.3.0"
serde_yaml = ">=0.8"
reqwest = ">=0.11"
log = "0.4"
lazy_static = "1"
serde = "1"
chrono = ">=0.4"
lazy-regex = ">=2"
env_logger = ">=0.10"
clap = "4,<5"
serde_json = "1"
tempfile = "3"
configparser = "3"
url = "2"
debian-changelog = ">=0.1"
debian-control = ">=0.1"
pyo3-log = { git = "https://github.com/jelmer/pyo3-log", branch = "pyo3-0.22" }
