[package]
name = "debian-analyzer"
version = { workspace = true }
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "Debian analyzer"
repository = "https://salsa.debian.org/jelmer/lintian-brush.git"
homepage = "https://salsa.debian.org/jelmer/lintian-brush"

[dependencies]
pyo3 = { workspace = true, features = ["auto-initialize", "serde", "chrono"] }
debversion = { workspace = true, features = ["serde"] }
log = { workspace = true }
lazy-regex.workspace = true
serde = { workspace = true, features = ["derive"] }
breezyshim.workspace = true
configparser.workspace = true
clap = { workspace = true, features = ["derive", "env", "suggestions", "cargo", "string"], optional = true }
env_logger = { workspace = true, optional = true }
serde_json.workspace = true
chrono = { workspace = true, features = ["serde"] }
distro-info = { version = ">=0.4.0" }
url = { workspace = true }
tempfile.workspace = true
maplit = "1.0.2"
lazy_static = "1.4.0"
debian-changelog = { workspace = true }

[features]
default = ["python", "cli"]
python = []
cli = ["dep:clap", "dep:env_logger"]

[workspace]
members = ["lintian-brush", "multiarch-hints", "lintian-brush-py", "debianize"]

[workspace.package]
version = "0.150.0"

[workspace.dependencies]
breezyshim = "0.1.34"
pyo3 = "0.19"
debversion = ">=0.1.8"
serde_yaml = ">=0.8"
reqwest = "0.11"
log = "0.4"
lazy_static = "1.4"
serde = "1"
chrono = "0.4"
lazy-regex = "2"
env_logger = "0.10"
pyo3-file = ">=0.5"
clap = "4"
serde_json = "1"
tempfile = "3"
configparser = "3.0.2"
url = "2.4"
debian-changelog = "0.1.1"

[lib]

[[bin]]
name = "detect-changelog-behaviour"
path = "src/bin/detect-changelog-behaviour.rs"
required-features = ["cli"]

[[bin]]
name = "deb-vcs-publish"
path = "src/bin/deb-vcs-publish.rs"
required-features = ["cli"]
