[package]
name = "lintian-brush"
version = "0.149.0"
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "Automatic lintian issue fixer"
repository = "https://salsa.debian.org/jelmer/lintian-brush.git"
homepage = "https://salsa.debian.org/jelmer/lintian-brush"

[dependencies]
pyo3 = { version = "0.19", features = ["auto-initialize"], optional = true }
serde_json = { version = "1"}
serde_yaml = { version = ">=0.8" }
serde = { version = "1", features = ["derive"] }
distro-info = { version = ">=0.4.0" }
chrono = { version = "0.4" }
log = "0.4.19"

[features]
default = ["svp", "python"]
svp = []
python = ["dep:pyo3"]

[workspace]
members = ["multiarch-hints", "lintian-brush-py"]
