[workspace]
# With resolve set to "2", dependent projects can't find debian-analyzer anymore.
resolver = "1"
members = ["lintian-brush", "multiarch-hints", "lintian-brush-py", "debianize", "debianize-py", "analyzer", "scrub-obsolete"]

[workspace.package]
version = "0.158.14"

[workspace.dependencies]
breezyshim = { version = ">=0.1.160", features = ["dirty-tracker"] }
#breezyshim = { path = "../breezyshim/trunk", features = ["dirty-tracker"] }
pyo3 = ">=0.22"
debversion = ">=0.3.0"
serde_yaml = ">=0.8"
reqwest = ">=0.11"
log = "0.4"
lazy_static = "1"
serde = "1"
chrono = ">=0.4"
lazy-regex = ">=2"
env_logger = ">=0.10"
clap = "4,<5"
serde_json = "1"
tempfile = "3"
configparser = "3"
url = "2"
debian-copyright = ">=0.1"
debian-changelog = ">=0.1"
debian-control = ">=0.1.34"
deb822-lossless = ">=0.1"
pyo3-log = ">=0.11"
maplit = "1"
buildlog-consultant = "0.0.42"
#upstream-ontologist = "0.1.39"
upstream-ontologist = { git = "https://github.com/jelmer/upstream-ontologist" }
sqlx = "0.8"

#debian-control = { path = "../deb822-lossless/debian-control" }
#deb822-lossless = { path = "../deb822-lossless" }
