[package]
name = "lintian-brush"
version = "0.149.0"
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "Automatic lintian issue fixer"
repository = "https://salsa.debian.org/jelmer/lintian-brush.git"
homepage = "https://salsa.debian.org/jelmer/lintian-brush"

[dependencies]
pyo3 = { workspace = true, features = ["auto-initialize", "serde", "chrono"], optional = true }
serde_json = { version = "1"}
serde_yaml = { version = ">=0.8" }
serde = { version = "1", features = ["derive"] }
distro-info = { version = ">=0.4.0" }
chrono = { version = "0.4" }
log = "0.4"
configparser = "3.0.2"
clap = { version = "4", features = ["derive", "env", "suggestions", "cargo"], optional = true }
env_logger = { version = "0.10.0", optional = true }
lazy-regex = "3.0.0"
debversion = { workspace = true, features = ["python-debian"] }
pyo3-file = "0.7.0"
breezyshim = { workspace = true }
indicatif = "0.17"
once_cell = "1.18.0"

[features]
default = ["svp", "python", "cli"]
svp = []
python = ["dep:pyo3"]
cli = ["dep:clap", "dep:env_logger"]

[workspace]
members = ["multiarch-hints", "lintian-brush-py"]

[workspace.dependencies]
breezyshim = "0.1.4"
pyo3 = "0.19"
debversion = ">=0.1.8"

[[bin]]
name = "lintian-brush"
required-features = ["cli"]
