[workspace]
resolver = "2"
members = ["lintian-brush", "multiarch-hints", "lintian-brush-py", "debianize", "debianize-py", "analyzer"]

[workspace.package]
version = "0.158.9"

[workspace.dependencies]
#breezyshim = { version = ">=0.1.160", features = ["dirty-tracker"] }
breezyshim = { path = "../breezyshim/trunk", features = ["dirty-tracker"] }
pyo3 = ">=0.22"
debversion = ">=0.3.0"
serde_yaml = ">=0.8"
reqwest = ">=0.11"
log = "0.4"
lazy_static = "1"
serde = "1"
chrono = ">=0.4"
lazy-regex = ">=2"
env_logger = ">=0.10"
clap = "4,<5"
serde_json = "1"
tempfile = "3"
configparser = "3"
url = "2"
debian-changelog = ">=0.1"
debian-control = ">=0.1"
#debian-control = { git = "https://github.com/jelmer/deb822-lossless" }
pyo3-log = ">=0.11"
maplit = "1"
buildlog-consultant = ">=0.0.39"
#upstream-ontologist = ">=0.1.38"
upstream-ontologist = { git = "https://github.com/jelmer/upstream-ontologist" }
