[workspace]
resolver = "2"
edition = "2021"
members = ["lintian-brush", "multiarch-hints", "lintian-brush-py", "debianize", "debianize-py", "analyzer"]

[workspace.package]
version = "0.155.0"

[workspace.dependencies]
breezyshim = ">=0.1.58"
pyo3 = ">=0.20"
debversion = ">=0.3.0"
serde_yaml = ">=0.8"
reqwest = "0.11"
log = "0.4"
lazy_static = "1.4"
serde = "1"
chrono = "0.4"
lazy-regex = "2"
env_logger = ">=0.10"
clap = "4,<4.5"
serde_json = "1"
tempfile = "3"
configparser = "3.0.2"
url = "2.4"
debian-changelog = "0.1"
debian-control = "0.1"
