[package]
name = "multiarch-hints"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
lazy_static = "1.4.0"
log = "0.4.19"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde = { version = "1.0.167", features = ["derive"] }
serde_yaml = "0.9.22"
xz2 = "0.1.7"
