[package]
name = "multiarch-hints"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
lazy_static = "1.4"
log = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
xz2 = "0.1"
