[package]
name = "lintian-brush"
version = { workspace = true }
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "Automatic lintian issue fixer"
repository = "https://salsa.debian.org/jelmer/lintian-brush.git"
homepage = "https://salsa.debian.org/jelmer/lintian-brush"

[dependencies]
pyo3 = { workspace = true, features = ["auto-initialize", "serde", "chrono"], optional = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
log = { workspace = true }
configparser.workspace = true
clap = { workspace = true, features = ["derive", "env", "suggestions", "cargo", "string"], optional = true }
env_logger = { workspace = true, optional = true }
lazy-regex = { workspace = true }
debversion = { workspace = true, features = ["python-debian"] }
breezyshim = { workspace = true }
indicatif = "0.17"
tempfile = { workspace = true }
url = { version = "2", features = ["serde"] }
lazy_static = { workspace = true }
debian-analyzer = { version = "0.150.0", path = ".." }
distro-info = "0.4.0"
debian-changelog = { workspace = true }

[features]
default = ["svp", "python", "cli"]
svp = []
python = ["dep:pyo3"]
cli = ["dep:clap", "dep:env_logger"]

[[bin]]
name = "lintian-brush"
required-features = ["cli"]

