def default_debianize_cache_dir() -> str: ...
def go_import_path_from_repo(url: str) -> str: ...
def write_changelog_template(
    path: str,
    source_name: str,
    version: str,
    author: tuple[str, str] | None,
    wnpp_bugs: list[tuple[str, int]] | None,
) -> None: ...
def source_name_from_directory_name(path: str) -> str: ...
def perl_package_name(name: str) -> str: ...
def python_source_package_name(name: str) -> str: ...
def python_binary_package_name(name: str) -> str: ...
