# Stub file for lintian_brush._lintian_brush_rs

from typing import Any

# Based on usage in patches.py
def strip_dep3_header(
    content: str,
) -> tuple[dict[str, Any] | None, str]: ...
def tree_has_non_patches_changes(path: str) -> bool: ...

# Based on usage in release_info.py
def parse_release_info(content: str) -> dict[str, Any]: ...

DEBHELPER_VERSIONS: dict[str, Any]
DPKG_VERSIONS: dict[str, Any]

# Based on usage in salsa.py
def guess_repository_url(package_name: str, vcs_type: str) -> str | None: ...

# Based on usage in vcs.py
def determine_gitlab_browser_url(url: str) -> str | None: ...
def determine_browser_url(url: str) -> str | None: ...
def canonicalize_vcs_browser_url(url: str) -> str: ...
