.TH DEB-VCS-PUBLISH "1" "February 2026" "deb-vcs-publish" "User Commands"
.SH NAME
deb\-vcs\-publish \- Publish a Debian package to its VCS repository
.SH SYNOPSIS
.B deb-vcs-publish
[\fIOPTIONS\fR] [\fIURL\fR]
.SH DESCRIPTION
deb-vcs-publish updates the Vcs-Git/Vcs-Browser fields in debian/control
based on the hosting location of the repository, creates the remote repository
if it does not exist yet, and pushes the current branch to it.
.SS "positional arguments:"
.TP
\fIURL\fR
URL of the VCS repository to publish to. If not specified, derived from
the existing Vcs-* fields in debian/control.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show program's version number and exit.
.TP
\fB\-d\fR, \fB\-\-directory\fR \fIDIR\fR
Directory to run in. Defaults to the current directory.
.TP
\fB\-\-no\-create\fR
Do not create the remote repository if it does not exist.
.TP
\fB\-\-force\fR
Overwrite existing Vcs-* fields in debian/control.
.TP
\fB\-\-debug\fR
Enable debug output.
.TP
\fB\-\-identity\fR
Print user identity that would be used when committing.
.SH "SEE ALSO"
\&\fIlintian-brush\fR\|(1)
.SH AUTHORS
Jelmer Vernooij <jelmer@debian.org>
