.TH deb-scrub-obsolete "1" "February 2026" "deb-scrub-obsolete" "User Commands"
.SH NAME
deb-scrub-obsolete \- scrub a Debian package of no longer necessary configuration
.SH SYNOPSIS
deb\-scrub\-obsolete [\fIOPTIONS\fR]
.SH DESCRIPTION
Scrub a Debian source package from unnecessary versioned depends, conflicts and maintscripts.
.PP
Specifically, it makes the following categories of changes:
.IP \[bu]
obsolete maintscript entries for upgrades from versions older than that in $compat_release
.IP \[bu]
depends on packages that are essential since $compat_release
.IP \[bu]
build-depends on packages that are build-essential since $compat_release
.IP \[bu]
replacing dependencies on "transitional dummy packages" with the real thing (if satisfiable since $compat_release)
.IP \[bu]
conflicts with packages that are gone since before $compat_release
.IP \[bu]
version constraints in build-depends or depends that are met by the package in $compat_release
.PP
This tool is separate from lintian-brush since unlike lintian-brush, it needs to take an archive-wide view of the package.
It is safe to run alongside lintian-brush and will only make changes when it finds constraints that are genuinely obsolete.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit.
.TP
\fB\-\-version\fR
Show program's version number and exit.
.TP
\fB\-d\fR, \fB\-\-directory\fR \fIDIR\fR
Directory to run in. Defaults to the current directory.
.TP
\fB\-\-no\-update\-changelog\fR
Do not update the changelog.
.TP
\fB\-\-update\-changelog\fR
Always update the changelog.
.TP
\fB\-u\fR, \fB\-\-upgrade\-release\fR \fIRELEASE\fR
Don't remove any constraints that are necessary for upgrading from RELEASE or
newer releases. This can either be a codename ("bookworm"), or an alias
("unstable", "old-old-stable"). Defaults to "oldstable".
For a full list of options, see \fBdistro-info\fR(1).
.TP
\fB\-c\fR, \fB\-\-compat\-release\fR \fIRELEASE\fR
Don't remove any constraints that are necessary for building on RELEASE or
newer releases. This can either be a codename ("bookworm"), or an alias
("unstable", "old-old-stable").
For a full list of options, see \fBdistro-info\fR(1).
.TP
\fB\-\-identity\fR
Print the identity (name and e\-mailaddress) that deb-scrub-obsolete will use
when committing changes, and exit.
.TP
\fB\-\-debug\fR
Print debugging information.
.TP
\fB\-\-keep\-minimum\-depends\-versions\fR
Keep minimum version constraints in dependencies, even when the constraint
is satisfied by the package version in $compat_release and thus technically
unnecessary.
.IP
Some teams deliberately maintain minimum version constraints to document
upstream requirements, track which dependency versions are needed for
backporting, or to express a semantic dependency on a specific feature
introduced in a particular version. In such cases, using this option avoids
accidentally removing constraints that carry intentional meaning beyond
mere historical necessity.
.SH ENVIRONMENT
.TP
\fBDEB_UPDATE_CHANGELOG\fR
Used to control whether the changelog should be updated, depending on whether
it is set to "leave", "update" or "auto". The --update-changelog and --no-update-changelog arguments
override this.
.TP
\fBCOMPAT_RELEASE\fR
Oldest Debian release to stay compatible with. Overridden by \fB\-\-compat\-release\fR.
.SH "SEE ALSO"
\&\fIlintian-brush.conf\fR\|(5)
\&\fIlintian-brush\fR\|(1)
.SH AUTHORS
Jelmer Vernooij <jelmer@debian.org>
