.TH deb-scrub-obsolete "1" "September 2020" "deb-scrub-obsolete 0.1" "User Commands"
.SH NAME
deb-scrub-obsolete \- scrub a Debian package of no longer necessary configuration
.SH SYNOPSIS
deb\-scrub\-obsolete [\-h] [\-\-no\-update\-changelog] [\-\-version] [\-\-upgrade\-release=RELEASE]
.SH DESCRIPTION
Scrub a Debian source package from unnecessary versioned depends, conflicts and maintscripts.
.PP
Specifically, it make the following categories of changes:
.IP \[bu]
obsolete maintscript entries for upgrades from versions older than that in $compat_release
.IP \[bu]
depends on packages that are essential since $compat_release
.IP \[bu]
build-depends on packages that are build-essential since $compat_release
.IP \[bu]
replacing dependencies on "transitional dummy packages" with the real thing (if satisfiable since $compat_release)
.IP \[bu]
conflicts with packages that are gone since before $compat_release
.IP \[bu]
version constraints in build-depends or depends that are met by the package in $compat_release
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-no\-update\-changelog\fR
Whether to update the changelog.
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-\-upgrade\-release=RELEASE\fR
Don't remove any constraints that are necessary for upgrading from RELEASE or
newer releases. This can either be a codename ("bookworm"), or an alias ("unstable", "old-old-stable").
For a full list options, see \fBdistro-info\fR(1).
.TP
\fB\-\-compat\-release=RELEASE\fR
Don't remove any constraints that are necessary for building on RELEASE or
newer releases. This can either be a codename ("bookworm"), or an alias ("unstable", "old-old-stable").
For a full list options, see \fBdistro-info\fR(1).
.TP
\fB\-\-identity\fR
Print the identity (name and e\-mailaddress) that apply-multiarch-hints will use when committing changes, and exit.
.TP
\fB\-\-debug\fR
Print debugging information
.TP
\fB\-\-keep-minimum-depends-versions\fR
Keep minimum version dependencies, even when unnecessary
.SH ENVIRONMENT
.TP
\fBDEB_UPDATE_CHANGELOG\fR
Used to control whether the changelog should be updated, depending on whether
it is set to "leave", "update" or "auto". The --update-changelog and --no-update-changelog arguments
override this.
.SH "SEE ALSO"
\&\fIlintian-brush.conf\fR\|(5)
\&\fIlintian-brush\fR\|(1)
.SH AUTHORS
Jelmer Vernooij <jelmer@debian.org>
