.TH DEB-VCS-PUBLISH "1" "November 2023" "deb-vcs-publish 0.150.0" "User Commands"
.SH NAME
deb\-vcs\-publish \- Publish a Debian package to its VCS repository
.SH SYNOPSIS
.B deb-vcs-publish
[\fI\,OPTIONS\/\fR] [\fI\,NO_CREATE\/\fR] [\fI\,FORCE\/\fR] [\fI\,PUSH\/\fR] [\fI\,URL\/\fR]
.SH DESCRIPTION
.SS "Arguments:"
.TP
[NO_CREATE]
Do not create the repository
.IP
[FORCE]
[PUSH]       Push branch
[URL]
.SH OPTIONS
.TP
\fB\-\-debug\fR
Enable debug output
.TP
\fB\-\-identity\fR
Print user identity that would be used when committing
.TP
\fB\-d\fR, \fB\-\-directory\fR <DIR>
directory to run in [default: .]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
