.TH DETECT-CHANGELOG-BEHAVIOUR "1" "February 2026" "detect-changelog-behaviour" "User Commands"
.SH NAME
detect-changelog-behaviour \- Detect changelog update behaviour
.SH SYNOPSIS
.B detect-changelog-behaviour
[\fIOPTIONS\fR] [\fIDIRECTORY\fR]
.SH DESCRIPTION
detect-changelog-behaviour inspects a Debian package's version control
configuration (e.g. gbp.conf) and heuristics to determine whether the
changelog is managed automatically (e.g. by "gbp dch") or manually updated.
It prints "true" if the changelog should be updated, or "false" if it is
managed automatically, and exits with a non-zero status if it cannot determine
the behaviour.
.SS "positional arguments:"
.TP
\fIDIRECTORY\fR
The directory to check. Defaults to the current directory.
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show program's version number and exit.
.TP
\fB\-\-verbose\fR
Be verbose.
.SH "SEE ALSO"
\&\fIlintian-brush\fR\|(1)
.SH AUTHORS
Jelmer Vernooij <jelmer@debian.org>
