.TH DETECT-CHANGELOG-BEHAVIOUR "1" "November 2023" "detect-changelog-behaviour 0.150.0" "User Commands"
.SH NAME
detect-changelog-behaviour \- Detect changelog behaviour
.SH SYNOPSIS
.B detect-changelog-behaviour
[\fI\,OPTIONS\/\fR] [\fI\,DIRECTORY\/\fR]
.SH DESCRIPTION
.SS "Arguments:"
.TP
[DIRECTORY]
The directory to check [default: .]
.SH OPTIONS
.TP
\fB\-\-verbose\fR
Be verbose
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
