# This file exists purely for backwards compatibility so that any repository
# having the old filename will continue to run the CI. GitLab CI does not follow
# regular symlinks, so the reference to the new file is done with a yaml rule.
#
# This file can be remove once the main repository and all forks have updated
# their CI configuration to point directly to new file 'debian/salsa-ci.yml'.
---
include:
  - local: 'debian/salsa-ci.yml'
