---
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml

variables:
  SALSA_CI_DISABLE_BLHC: 1
  # Build for experimental distribution
  # RELEASE: 'experimental'

stages:
  - lint
  - provisioning
  - build
  - test
  - publish

cargo-fmt:
  stage: lint
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

ruff:
  stage: lint
  image: python:latest
  script:
    - pip install ruff
    - ruff check .
    - ruff format --check .
  cache:
    paths:
      - ~/.cache/pip
