[package]
name = "lintian-brush-py"
version = "0.0.0"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://salsa.debian.org/jelmer/lintian-brush"
homepage = "https://salsa.debian.org/jelmer/lintian-brush"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module", "chrono", "serde"] }
lintian-brush = { path = ".." }
serde_json = "1"
chrono = "0.4"
multiarch-hints = { path = "../multiarch-hints" }
pyo3-log = "0.8.2"
debversion = { workspace = true, features = ["python-debian"] }
breezyshim = { workspace = true }
