---
name: Build and Publish Docker Image

on:
  # run it on push to the default repository branch
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'  # Daily 6AM UTC build

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build lintian-brush image
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile.lintian-brush"
          tags: |
            ghcr.io/jelmer/lintian-brush:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build deb-scrub-obsolete image
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile.deb-scrub-obsolete"
          tags: |
            ghcr.io/jelmer/deb-scrub-obsolete:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build debianize image
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile.debianize"
          tags: |
            ghcr.io/jelmer/debianize:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build apply-multiarch-hints image
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile.apply-multiarch-hints"
          tags: |
            ghcr.io/jelmer/apply-multiarch-hints:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}
